<section id="blog" class="section section-blog">
    <div class="container">
        <h2 class="section-title"><span>Our Blog</span></h2>
        <div class="row">
            <div class="col-md-6">
                <article class="hentry post">
                    <div class="row">
                        <div class="entry-thumbnail col-lg-4 col-md-5 col-sm-4">
                            <a href="#" class="hover-effect">
                                <img src="http://placehold.it/165x165" alt="" />
                                <span class="overlay"><i class="fa fa-plus"></i></span>
                            </a>
                        </div>
                        <div class="col-lg-8 col-md-7 col-sm-8">
                            <header class="entry-header">
                                <h2 class="entry-title"><a href="#">Sample blog title</a></h2>
                                <div class="entry-meta">By <a href="#">Jackie Lord</a> in <a href="#">Category</a></div>
                            </header>
                            <div class="entry-content">
                                <p>Pellentesque eleifend amet scelerisque convallis. Aenean eget metus non erat 
                                    suscipit accumsan.
                                </p>
                                <a href="#" class="more"><span class="btn btn-primary">Continue Reading</span></a>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
            <div class="col-md-6">
                <article class="hentry post">
                    <div class="row">
                        <div class="entry-thumbnail col-lg-4 col-md-5 col-sm-4">
                            <a href="#" class="hover-effect">
                                <img src="http://placehold.it/165x165" alt="" />
                                <span class="overlay"><i class="fa fa-plus"></i></span>
                            </a>
                        </div>
                        <div class="col-lg-8 col-md-7 col-sm-8">
                            <header class="entry-header">
                                <h2 class="entry-title"><a href="#">Sample blog title</a></h2>
                                <div class="entry-meta">By <a href="#">Jackie Lord</a> in <a href="#">Category</a></div>
                            </header>
                            <div class="entry-content">
                                <p>Pellentesque eleifend amet scelerisque convallis. Aenean eget metus non erat suscipit 
                                    accumsan.
                                </p>
                                <a href="#" class="more"><span class="btn btn-primary">Continue Reading</span></a>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>