<script>
    (function($) {
        $(function() {
            $("#clients").parallax({
                imageSrc        : 'images/dark-party-crowd-dancing-1920x550.jpg',
                naturalWidth    : 1920,
                naturalHeight   : 600,
                iosFix          : true,
                androidFix      : true,
                bleed           : 20
            });
        });
    })(jQuery);

</script>

<section id="clients" class="section section-hilite section-our-clients">
    <div class="container">
        <h2 class="section-title">Our <span>Clients &amp; Friends</span></h2>
        <div class="row">
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="#"><img src="http://placehold.it/165x80" alt="" /></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="#"><img src="http://placehold.it/165x80" alt="" /></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="#"><img src="http://placehold.it/165x80" alt="" /></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="#"><img src="http://placehold.it/165x80" alt="" /></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="#"><img src="http://placehold.it/165x80" alt="" /></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="#"><img src="http://placehold.it/165x80" alt="" /></a>
            </div>
        </div>
    </div>
</section>