<section id="clients" class="section section-hilite section-our-clients">
    <div class="container">
        <h2 class="section-title"><span>Our Clients</span></h2>
        <div class="row">
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="#"><img src="http://placehold.it/165x80" alt="" /></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="#"><img src="http://placehold.it/165x80" alt="" /></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="#"><img src="http://placehold.it/165x80" alt="" /></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="#"><img src="http://placehold.it/165x80" alt="" /></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="#"><img src="http://placehold.it/165x80" alt="" /></a>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <a href="#"><img src="http://placehold.it/165x80" alt="" /></a>
            </div>
        </div>
    </div>
</section>