<section id="contact" class="section section-center section-contact">
    <div class="container">
        <h2 class="section-title"><span>Contact Us</span> to Connect</h2>
        <p style="color: white;">Want to say hello? Want to know more about us? Give us a call or drop us an email and we will get back 
            to you as soon as we can.
        </p>
        <div class="main-action">
            <form role="form" method="post" action="php/contact-form.php">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="sr-only">Subject</label>
                            <input type="text" class="form-control" placeholder="Subject" name="subject">
                        </div>
                        <div class="form-group">
                            <label class="sr-only">Name</label>
                            <input type="text" class="form-control" placeholder="Name" name="name">
                        </div>
                        <div class="form-group">
                            <label class="sr-only">Email</label>
                            <input type="email" class="form-control" placeholder="Email" name="email">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="sr-only">Message</label>
                            <textarea class="form-control" placeholder="Message" style="height: 100px" rows="6" name="message"></textarea>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-default">Send message</button>
            </form>
        </div>
    </div>
</section>