<section class="section section-center section-cta">
	<div class="container">
		<h2 class="section-title"><span>Check Out Our Gear!</span></h2>
		<p>Tatonka Backline Co. (formerly Soundcolor Productions, LLC) is the best choice when it comes to sourcing your 
			backline rental needs. We have a full line of industry-standard gear at the most competitve prices. We offer daily, weekly and long term rates. Festival discounts are available. Contact us and see what we can do for you today!
		</p>
		<div class="main-action row">
			<div class="col-md-3 col-md-offset-3 col-sm-4 col-sm-offset-2">					
				<a href="#contact" class="smooth-scroll btn btn-lg btn-block btn-danger">View Our Gear List</a>
			</div>
			<div class="col-md-3 col-sm-4">
				<a href="#portfolio" class="smooth-scroll btn btn-lg btn-block btn-default">Contact Us</a>
			</div>
		</div>
	</div>
</section>