<div class="modal fade" id="project-modal" tabindex="-1" role="dialog" aria-labelledby="project-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title equipment-title" id="project-modal-label"></h4>
            </div>
            <div class="modal-body">
                <article class="single-project">
                    <div class="project-thumbnail">
                        <!--<div class="item">
                            <img src="http://placehold.it/800x600" />
                        </div><!-- end .item -->
                        <!-- <div id="project-thumbnail-carousel-1" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="item active"><img src="http://placehold.it/800x600" /></div>
                                <div class="item"><img src="http://placehold.it/800x600" /></div>
                                <div class="item"><img src="http://placehold.it/800x600" /></div>
                            </div>
                            <ol class="carousel-indicators">
                                <li data-target="#project-thumbnail-carousel-1" data-slide-to="0" class="active"></li>
                                <li data-target="#project-thumbnail-carousel-1" data-slide-to="1"></li>
                                <li data-target="#project-thumbnail-carousel-1" data-slide-to="2"></li>
                            </ol>
                            <a class="left carousel-control" href="#project-thumbnail-carousel-1" data-slide="prev">
                                <span class="fa fa-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#project-thumbnail-carousel-1" data-slide="next">
                                <span class="fa fa-chevron-right"></span>
                            </a>
                        </div> -->
                    </div><!-- end .project-thumbnail -->
                    <div class="row">
                        <!-- <div class="col-md-4">
                            <button type="button" class="btn btn-block btn-primary">Launch Project</button>
                            <ul class="list-unstyled project-info">
                                <li><strong>Type</strong> <span class="pull-right">Web Design</span></li>
                                <li><strong>Client</strong> <span class="pull-right">Google</span></li>
                                <li><strong>Year</strong> <span class="pull-right">2014</span></li>
                            </ul>
                        </div> -->
                        <div class="col-md-12">
                            <div class="equipment-tagline">
                                <p style='font-style: italic;'>We are constantly adding more gear every day. Contact us using the form 
                                    at the bottom of the page if you don't see what you're looking for!
                                </p>
                            </div><!-- end .equipment-tagline -->
                            <div class="equipment-description"></div>
                        </div>
                    </div><!-- end .row -->
                </article>
            </div><!-- end .modal-body -->
        </div><!-- end .modal-content -->
    </div><!-- end .modal-dialog -->
</div><!-- end .modal -->