<section id="equipment" class="section section-portfolio">
    <div class="container">
        <h2 class="section-title"><span>Check Out Our Gear</span></h2>
        <ul id="filters">
            <li><a href="#" data-filter="*">All</a></li>
            <li>/</li>
            <li><a href="#" data-filter=".drums-perc">Drumkits &amp; Percussion</a></li>
            <li>/</li>
            <li><a href="#" data-filter=".keyboards-organs">Keyboards &amp; Hammond Organs</a></li>
            <li>/</li>
            <li><a href="#" data-filter=".photography">Photography</a></li>
            <li>/</li>
            <li><a href="#" data-filter=".motion">Motion keyboards-organss</a></li>
            <li>/</li>
            <li><a href="#" data-filter=".branding">Branding</a></li>
        </ul>

        <script>
            (function($) {
                $(function() {

                    $("#equipment .hover-effect").on("click", function() {
                        //establish default null values for modal fields
                        var modals = {
                            description : null,
                            tagline : null
                        };

                        //store the category of item that has been clicked
                        var category = $(this).parents("article").attr("data-modal");

                        switch (category) {
                            //for drums products
                            case "drums-modal" :
                                modals.description = "drums description" //set description
                                modals.tagline = "drums"; //set tagline

                                //write the content into the modal fields
                                $(".equipment-description").html(modals.description);
                                $(".equipment-tagline").html(modals.tagline);

                            break;//end case "drums-modal"

                            //for keyboards products
                            case "keyboards-modal" :
                                modals.description = "keys description" //set description
                                modals.tagline = "keyboards"; //set tagline

                                //write the content into the modal fields
                                $(".equipment-description").html(modals.description);
                                $(".equipment-tagline").html(modals.tagline);

                            break;//end case "keyboards-modal"
                        }// end switch
                    });
                });
            })(jQuery);

        </script>

        <div class="portfolio-isotope row">
            <article class="post col-md-3 col-sm-6 portfolio-item branding photography drums-perc" data-modal="drums-modal">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item motion keyboards-organs" data-modal="keyboards-modal">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item branding drums-perc">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item photography keyboards-organs">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item motion drums-perc">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item branding keyboards-organs">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item motion photography drums-perc">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item photography motion branding keyboards-organs">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
        </div>
    </div>
</section>