<section id="equipment" class="section section-portfolio">
    <div class="container">
        <h2 class="section-title"><span>Check Out Our Gear</span></h2>
        <ul id="filters">
            <li><a href="#" data-filter="*">All</a></li>
            <li>/</li>
            <li><a href="#" data-filter=".drums-perc">Drumkits &amp; Percussion</a></li>
            <li>/</li>
            <li><a href="#" data-filter=".keyboards-organs">Keyboards &amp; Hammond Organs</a></li>
            <li>/</li>
            <li><a href="#" data-filter=".photography">Photography</a></li>
            <li>/</li>
            <li><a href="#" data-filter=".motion">Motion keyboards-organss</a></li>
            <li>/</li>
            <li><a href="#" data-filter=".branding">Branding</a></li>
        </ul>

        <script>
            (function($) {
                $(function() {
                    //TODO: SO FUCKING TIRED BUT WRAP THIS IN AN ONCLICK EVENT ON THE ANCHOR AND YOURE GOLDEN MY FRIEND!

                    var modals = {
                        description : null,
                        tagline : null
                    };

                    var category = $("#equipment .post").attr("data-modal");

                    switch (category) {
                        case "drums-modal" :
                            modals.tagline = "drums";

                            $(".tagline").html(modals.tagline);
                        break;

                        case "keyboards-modal" :
                            modals.tagline = "keyboards";

                            $(".tagline").html(modals.tagline);
                        break;
                    }

                    /*$(".drums-modal").on("click", function() {
                        modals.tagline = "drums";

                        $(".tagline").html(modals.tagline);
                    });

                    $(".keyboards-modal").on("click", function() {
                        modals.tagline = "keys";

                        $(".tagline").html(modals.tagline);
                    });*/

                    
                });
            })(jQuery);

        </script>

        <div class="portfolio-isotope row">
            <article class="post col-md-3 col-sm-6 portfolio-item branding photography drums-perc" data-modal="drums-modal">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item motion keyboards-organs" data-modal="keyboards-modal">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item branding drums-perc">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item photography keyboards-organs">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item motion drums-perc">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item branding keyboards-organs">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item motion photography drums-perc">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
            <article class="post col-md-3 col-sm-6 portfolio-item photography motion branding keyboards-organs">
                <div class="entry-thumbnail">
                    <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                        <img src="http://placehold.it/400x300" alt="" />
                        <span class="overlay"><i class="fa fa-plus"></i></span>
                    </a>
                </div>
            </article>
        </div>
    </div>
</section>