<section id="features" class="section section-center section-hilite section-features">
    <div class="container">
        <h2 class="section-title"><span>How it works?</span></h2>
        <div class="row">

            <div class="col-md-4 col-sm-6">
                 <div class="icon-wrap"><img src="http://placehold.it/128x128" alt=""></div>
                <h4>Subheading</h4>
                <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
            </div>

            <div class="col-md-4 col-sm-6">
                <div class="icon-wrap"><img src="http://placehold.it/128x128" alt=""></div>
                <h4>Subheading</h4>
                <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
            </div>

            <div class="col-md-4 col-sm-6">
                <div class="icon-wrap"><img src="http://placehold.it/128x128" alt=""></div>
                <h4>Subheading</h4>
                <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
            </div>

            <div class="col-md-4 col-sm-6">
                <div class="icon-wrap"><img src="http://placehold.it/128x128" alt=""></div>
                <h4>Subheading</h4>
                <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
            </div>

            <div class="col-md-4 col-sm-6">
                <div class="icon-wrap"><img src="http://placehold.it/128x128" alt=""></div>
                <h4>Subheading</h4>
                <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
            </div>

            <div class="col-md-4 col-sm-6">
                <div class="icon-wrap"><img src="http://placehold.it/128x128" alt=""></div>
                <h4>Subheading</h4>
                <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
            </div>
        </div>
    </div>
</section>