<section id="carousel-1" class="carousel slide section-slide" data-ride="carousel">
	<div class="carousel-inner">
      	<div class="item active" style="background: url(images/raw/bg-1.jpg);">
			<div class="container"><img src="http://placehold.it/640x340" alt="First slide"></div>
      	</div>
        <div class="item" style="background: url(images/raw/bg-2.jpg);">
        	<div class="container"><img src="http://placehold.it/640x340" alt="Second slide"></div>
        </div>
        <div class="item" style="background: url(images/raw/bg-3.jpg);">
        	<div class="container"><img src="http://placehold.it/640x340" alt="Third slide"></div>
        </div>
	</div>
	<a class="left carousel-control" href="#carousel-1" data-slide="prev"><span class="fa fa-chevron-left"></span></a>
	<a class="right carousel-control" href="#carousel-1" data-slide="next"><span class="fa fa-chevron-right"></span></a>
</section>