<section id="carousel-1" class="carousel slide section-slide" data-ride="carousel">
	<div class="carousel-inner">
      	<div class="item active first" style="background: url(images/live-crowd-lights-1920x550.jpg);">
			<div class="container">
                <h1>Looking for <span>Backline Gear?</span></h1>
                <p>We've Got You Covered! Click the button below to see a current list of all our gear</p>
                <a href="#equipment" class="smooth-scroll" style="text-decoration: none;">
                    <button class="smooth-scroll btn btn-lg btn-block btn-danger">See the Gear List</button>
                </a>

            </div>
      	</div>
        <div class="item second" style="background: url(images/piano-keys-1920x550.jpg);">
        	<div class="container">
                <h1><span>Special Requests?</span> We Can Do That!</h1>
                <p>Tatonka Backline Co. will strive to fulfill your request, big or small. Contact us today to let us know 
                    what you need!
                </p>
                <a href="#contact" class="smooth-scroll" style="text-decoration: none;">
                    <button class="smooth-scroll btn btn-lg btn-block btn-default">Contact Tatonka Backline Co.</button>
                </a>
            </div>
        </div>
        <div class="item third" style="background: url(images/red-guitar-1920x550.jpg);">
        	<div class="container">
                <h1><span>Connect With Us</span> on Social Media!</h1>
                <p>Share your favorite photos and articles with us, see where we're at, and check out who we're working with!</p>
                <div class="social-icon col-xs-6">
                    <a href="https://www.facebook.com/tatonkabackline" style="display: inline;">
                        <img src="images/facebook-logo-200x200.png" style="float: right;" alt="">
                    </a>

                </div>
                <div class="social-icon col-xs-6">
                    <a href="https://twitter.com/tatonkabackline" style="display: inline;">
                        <img src="images/twitter-logo-200x200.png" style="float: left;" alt="">
                    </a>

                </div>
            </div>
        </div>
	</div><!-- end .carousel-inner -->
	<a class="left carousel-control" href="#carousel-1" data-slide="prev"><span class="fa fa-chevron-left"></span></a>
	<a class="right carousel-control" href="#carousel-1" data-slide="next"><span class="fa fa-chevron-right"></span></a>
</section>