<section id="portfolio" class="section section-portfolio">
        <div class="container">
            <h2 class="section-title"><span>Recent Works.</span></h2>
            <ul id="filters">
                <li><a href="#" data-filter="*">All</a></li>
                <li>/</li>
                <li><a href="#" data-filter=".web">Web Design</a></li>
                <li>/</li>
                <li><a href="#" data-filter=".graphic">Graphic Design</a></li>
                <li>/</li>
                <li><a href="#" data-filter=".photography">Photography</a></li>
                <li>/</li>
                <li><a href="#" data-filter=".motion">Motion Graphics</a></li>
                <li>/</li>
                <li><a href="#" data-filter=".branding">Branding</a></li>
            </ul>

            <div class="portfolio-isotope row">
                <article class="post col-md-3 col-sm-6 portfolio-item branding photography web">
                    <div class="entry-thumbnail">
                        <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                            <img src="http://placehold.it/400x300" alt="" />
                            <span class="overlay"><i class="fa fa-plus"></i></span>
                        </a>
                    </div>
                </article>
                <article class="post col-md-3 col-sm-6 portfolio-item motion graphic">
                    <div class="entry-thumbnail">
                        <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                            <img src="http://placehold.it/400x300" alt="" />
                            <span class="overlay"><i class="fa fa-plus"></i></span>
                        </a>
                    </div>
                </article>
                <article class="post col-md-3 col-sm-6 portfolio-item branding web">
                    <div class="entry-thumbnail">
                        <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                            <img src="http://placehold.it/400x300" alt="" />
                            <span class="overlay"><i class="fa fa-plus"></i></span>
                        </a>
                    </div>
                </article>
                <article class="post col-md-3 col-sm-6 portfolio-item photography graphic">
                    <div class="entry-thumbnail">
                        <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                            <img src="http://placehold.it/400x300" alt="" />
                            <span class="overlay"><i class="fa fa-plus"></i></span>
                        </a>
                    </div>
                </article>
                <article class="post col-md-3 col-sm-6 portfolio-item motion web">
                    <div class="entry-thumbnail">
                        <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                            <img src="http://placehold.it/400x300" alt="" />
                            <span class="overlay"><i class="fa fa-plus"></i></span>
                        </a>
                    </div>
                </article>
                <article class="post col-md-3 col-sm-6 portfolio-item branding graphic">
                    <div class="entry-thumbnail">
                        <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                            <img src="http://placehold.it/400x300" alt="" />
                            <span class="overlay"><i class="fa fa-plus"></i></span>
                        </a>
                    </div>
                </article>
                <article class="post col-md-3 col-sm-6 portfolio-item motion photography web">
                    <div class="entry-thumbnail">
                        <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                            <img src="http://placehold.it/400x300" alt="" />
                            <span class="overlay"><i class="fa fa-plus"></i></span>
                        </a>
                    </div>
                </article>
                <article class="post col-md-3 col-sm-6 portfolio-item photography motion branding graphic">
                    <div class="entry-thumbnail">
                        <a href="#" class="hover-effect" data-toggle="modal" data-target="#project-modal">
                            <img src="http://placehold.it/400x300" alt="" />
                            <span class="overlay"><i class="fa fa-plus"></i></span>
                        </a>
                    </div>
                </article>
            </div>
        </div>
    </section>