<section id="pricing" class="section section-center section-pricing">
    <div class="container">
        <h2 class="section-title"><span>Pricing Table Made Easy</span></h2>
        <div class="pricing-table">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="panel panel-default">
                        <header class="panel-heading">
                            <h1>Bronze</h1>
                            <div class="the-price">$5 <span class="subscript">/ month</span></div>
                        </header>
                        <div class="panel-body">
                            <table class="table">
                                <tbody>
                                    <tr><td>1 Account</td></tr>
                                    <tr class="active"><td>1 Project</td></tr>
                                    <tr><td>50K API Access</td></tr>
                                    <tr class="active"><td>50MB Storage</td></tr>
                                    <tr><td>Custom Cloud Services</td></tr>
                                    <tr class="active"><td>Weekly Reports</td></tr>
                                </tbody>
                            </table>
                        </div>
                        <footer class="panel-footer"><a href="#" class="btn btn-default">Sign up now</a></footer>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="panel panel-default">
                        <header class="panel-heading">
                            <h1>Silver</h1>
                            <div class="the-price">$10 <span class="subscript">/ month</span></div>
                        </header>
                        <div class="panel-body">
                            <table class="table">
                                <tbody>
                                    <tr><td>1 Account</td></tr>
                                    <tr class="active"><td>3 Project</td></tr>
                                    <tr><td>100K API Access</td></tr>
                                    <tr class="active"><td>100MB Storage</td></tr>
                                    <tr><td>Custom Cloud Services</td></tr>
                                    <tr class="active"><td>Weekly Reports</td></tr>
                                </tbody>
                            </table>
                        </div>
                        <footer class="panel-footer"><a href="#" class="btn btn-default">Sign up now</a></footer>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="panel panel-primary">
                        <header class="panel-heading">
                            <h1>Gold</h1>
                            <div class="the-price">$20 <span class="subscript">/ month</span></div>
                        </header>
                        <div class="panel-body">
                            <table class="table">
                                <tbody>
                                    <tr><td>2 Account</td></tr>
                                    <tr class="active"><td>5 Project</td></tr>
                                    <tr><td>100K API Access</td></tr>
                                    <tr class="active"><td>200MB Storage</td></tr>
                                    <tr><td>Custom Cloud Services</td></tr>
                                    <tr class="active"><td>Weekly Reports</td></tr>
                                </tbody>
                            </table>
                        </div>
                        <footer class="panel-footer"><a href="#" class="btn btn-primary">Sign up now</a></footer>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="panel panel-default">
                        <header class="panel-heading">
                            <h1>Diamond</h1>
                            <div class="the-price">$35 <span class="subscript">/ month</span></div>
                        </header>
                        <div class="panel-body">
                            
                            <table class="table">
                                <tbody>
                                    <tr><td>5 Account</td></tr>
                                    <tr class="active"><td>20 Project</td></tr>
                                    <tr><td>300K API Access</td></tr>
                                    <tr class="active"><td>500MB Storage</td></tr>
                                    <tr><td>Custom Cloud Services</td></tr>
                                    <tr class="active"><td>Weekly Reports</td></tr>
                                </tbody>
                            </table>
                        </div>
                        <footer class="panel-footer"><a href="#" class="btn btn-default">Sign up now</a></footer>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>