<script>
    (function($) {
        $(function() {
            $("#services").parallax({
                imageSrc        : 'images/bw-guitar-rotated-1920x850.jpg',
                naturalWidth    : 1920,
                naturalHeight   : 600,
                iosFix          : true,
                androidFix      : true,
                bleed           : 20
            });

        });

        
    })(jQuery);
    

</script>

<section id="services" class="section section-center section-hilite section-features">
    <div class="container">
        <h2 class="section-title"><span>What Can We Do For You?</span></h2>
        <div class="row">

            <div class="col-md-4 col-sm-6">
                 <div class="icon-wrap"><img src="images/full-circle.png" alt=""></div>
                <h4>Equipment Rental</h4>
                <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
            </div>

            <div class="col-md-4 col-sm-6">
                <div class="icon-wrap"><img src="images/half-circle.png" alt=""></div>
                <h4>Specialized Requests</h4>
                <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
            </div>

            <div class="col-md-4 col-sm-6">
                <div class="icon-wrap"><img src="images/random-circle.png" alt=""></div>
                <h4>Music Production</h4>
                <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>
            </div>
        </div>
    </div>
</section>