<section id="team" class="section section-center section-hilite section-team">
        <div class="container">
            <h2 class="section-title"><span>Our Funny Team</span></h2>
            <div class="row">
                <div class="col-md-2 col-sm-4 col-xs-6">
                    <img src="http://placehold.it/300x300">
                    <h5>Rihanna</h5>
                </div>
                
                <div class="col-md-2 col-sm-4 col-xs-6">
                    <img src="http://placehold.it/300x300">
                    <h5>Marry</h5>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6">
                    <img src="http://placehold.it/300x300">
                    <h5>Ronaldo</h5>
                </div>
                
                <div class="col-md-2 col-sm-4 col-xs-6">
                    <img src="http://placehold.it/300x300">
                    <h5>Jackie Lord</h5>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6">
                    <img src="http://placehold.it/300x300">
                    <h5>David Beckham</h5>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6">
                    <img src="http://placehold.it/300x300">
                    <h5>John Doe</h5>
                </div>
            </div>
        </div>
    </section>