<section id="testimonials" class="section section-center section-hilite section-testimonial">
    <div class="container">
        <h2 class="section-title"><span>What our clients say?</span></h2>
        <i class="fa fa-quote-left fa-3x"></i>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="item active">
                    <blockquote>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                    </blockquote>
                </div>
                <div class="item">
                    <blockquote>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                    </blockquote>
                </div>
                <div class="item">
                    <blockquote>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                    </blockquote>
                </div>
            </div>

            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active">
                    <img src="http://placehold.it/64x64" width="64" height="64" alt="" class="img-circle">
                </li>
                <li data-target="#carousel-example-generic" data-slide-to="1">
                    <img src="http://placehold.it/64x64" width="64" height="64" alt="" class="img-circle">
                </li>
                <li data-target="#carousel-example-generic" data-slide-to="2">
                    <img src="http://placehold.it/64x64" width="64" height="64" alt="" class="img-circle">
                </li>
            </ol>
        </div>
    </div>
</section>