<!DOCTYPE html>
<html lang="en">

    <?php include('includes/layout/head.phtml'); ?>

  	<body>
    	<div id="page">

            <?php include('includes/layout/header.phtml'); ?>

      		<?php include('includes/layout/main-content.phtml'); ?>

            <?php include('includes/layout/footer.phtml'); ?>

        </div><!-- end #page -->

        <?php include('includes/modules/scroll-to-top.phtml'); ?>
  
        <?php include('includes/bottom-script-container.phtml'); ?>
    </body>
</html>