<footer id="footer" class="site-footer">
    <div class="container">

        <div id="sidebar-footer-1">
            <div class="row">

                <aside class="widget col-md-3 col-sm-6 mobile-hide">
                    <h5 class="widget-title">About Us</h5>
                    <p>Tatonka Backline Co. (formerly Soundcolor Productions, LLC) is the best choice when it comes to 
                        sourcing your backline rental needs.
                    </p>
                </aside>

                <aside class="widget col-md-3 col-sm-6">
                    <h5 class="widget-title">Contact</h5>
                    <div class="textwidget">
                        <span class="business-name">Tatonka Backline Co.</span>
                        <div class="adr">
                            <span class="street-address">422 N. Surrey</span>,
                            <span class="locality">Missoula</span>,
                            <span class="region">MT</span>
                            <span class="postal-code">59808</span>
                        </div>
                        <span>Phone: 406-531-6078</span>
                    </div>
                </aside>

                <aside class="widget col-md-3 col-sm-6 mobile-hide">
                    <h5 class="widget-title">Special Requests?</h5>
                    <p>No request is too big or small for our dedicated team. Contact us to get started today!</p>
                </aside>

                <aside class="widget col-md-3 col-sm-6">
                    <h5 class="widget-title">Get in touch</h5>
                    <a href="mailto:admin@tatonkabackline.com">admin@tatonkabackline.com</a>
                    <ul class="social-links">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    </ul>
                </aside>

            </div>
        </div>

        <script>
            //set current year in footer copyright statement
            (function($) {
                $(function() {
                    var currentYear = new Date().getFullYear();

                    $("span.year").append(currentYear);
                });
            })(jQuery);

        </script>

        <div class="copyright">
            <p>&copy; <span class="year"></span> Tatonka Backline Co.</p>
            <p>Website by <a href="https://www.linkedin.com/pub/marcus-windecker/9a/256/b23" target="_blank">M. Windecker</a></p>
        </div><!-- end .copyright -->
    </div>
</footer>