<header id="header" class="site-header">
	<nav id="topbar" class="site-topbar visible-lg visible-md">
		<div class="container">
			<div class="row">
			  	<div class="col-sm-6">Questions? Call us toll free: +1 234 4567 890</div>
		  		<div class="social-links col-sm-6">
				    <a href="#"><i class="fa fa-facebook"></i></a>
				    <a href="#"><i class="fa fa-twitter"></i></a>
				    <a href="#"><i class="fa fa-google-plus"></i></a>
				    <a href="#"><i class="fa fa-pinterest"></i></a>
		  		</div>
			</div>
		</div>
	</nav>

	<nav id="navbar" class="site-navbar navbar navbar-static-top" role="navigation">
	  	<div class="container">
	    	<div class="navbar-header">
	      		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
	        		<span class="sr-only">Toggle navigation</span>
	        		<i class="fa fa-bars"></i>
	      		</button>
	      		<h1 class="navbar-brand"><i class="fa fa-power-off"></i> <a href="index.html">Start</a></h1>
			</div>
	    	<div class="collapse navbar-collapse" id="navbar-collapse-1">
	      		<ul id="navigation" class="nav navbar-nav navbar-right">
	                <li class="active"><a href="#header" class="current">Home</a></li>
	                <li><a href="#features">Features</a></li>
	                <li><a href="#portfolio">Portfolio</a></li>
	                <li><a href="#testimonials">Testimonials</a></li>
	                <li><a href="#blog">Blog</a></li>
	                <li><a href="#clients">Clients</a></li>
	                <li><a href="#contact">Contact</a></li>
	      		</ul>
	    	</div>
	  	</div>
	</nav>
</header>