<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Tatonka Backline | Your Best Option for Backline Rentals in Missoula</title>
	<link rel="shortcut icon" href="images/favicon.ico" /> 

	<link href="css/template.css" rel="stylesheet">

	<script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->
</head>