<main id="main" class="site-main">
	
    <?php include('includes/blocks/main-slider.phtml'); ?>

    <?php include('includes/blocks/cta.phtml'); ?>

    <?php include('includes/blocks/services.phtml'); ?>

    <?php include('includes/blocks/equipment.phtml'); ?>

    <!-- Project Modal -->
    <?php include('includes/blocks/equipment-modal.phtml'); ?>

    <?php include('includes/blocks/testimonials.phtml'); ?>

    <?php include('includes/blocks/clients.phtml'); ?>

    <?php include('includes/blocks/contact.phtml'); ?>
    
</main>