<main id="main" class="site-main">
	
    <?php include('includes/blocks/main-slider.phtml'); ?>

    <?php include('includes/blocks/cta.phtml'); ?>

    <?php include('includes/blocks/features.phtml'); ?>

    <?php include('includes/blocks/gear-list.phtml'); ?>

    <!-- Project Modal -->
    <?php include('includes/blocks/gear-list-modal.phtml'); ?>

    <?php include('includes/blocks/testimonials.phtml'); ?>

    <?php include('includes/blocks/pricing.phtml'); ?>

    <?php include('includes/blocks/team.phtml'); ?>

    <?php include('includes/blocks/blog.phtml'); ?>

    <?php include('includes/blocks/clients.phtml'); ?>

    <?php include('includes/blocks/contact.phtml'); ?>
    
</main>