<main id="main" class="site-main">
	
    <?php include('includes/blocks/main-slider.phtml'); ?>

    <section class="section section-center section-cta">
      	<div class="container">
        	<h2 class="section-title"><span>Ready to Start?</span></h2>
        	<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, 
        		tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
        	</p>
        	<div class="main-action row">
              	<div class="col-md-3 col-md-offset-3 col-sm-4 col-sm-offset-2">
              		<a href="#contact" class="smooth-scroll btn btn-lg btn-block btn-danger">Request Quote</a>
              	</div>
              	<div class="col-md-3 col-sm-4">
              		<a href="#portfolio" class="smooth-scroll btn btn-lg btn-block btn-default">View Portfolio</a>
              	</div>
            </div>
      	</div>
    </section>

    <?php include('includes/blocks/features.phtml'); ?>

    <?php include('includes/blocks/portfolio.phtml'); ?>

    <!-- Project Modal -->
    <?php include('includes/blocks/portfolio-modal.phtml'); ?>

    <?php include('includes/blocks/testimonials.phtml'); ?>

    <?php include('includes/blocks/pricing.phtml'); ?>

    <?php include('includes/blocks/team.phtml'); ?>

    <?php include('includes/blocks/blog.phtml'); ?>

    <?php include('includes/blocks/clients.phtml'); ?>

    <?php include('includes/blocks/contact.phtml'); ?>
    
</main>