<script>//TODO: async any scripts that can be. decide where to load new scripts to be implemented</script>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="assets/js/bootstrap-3.1.1.min.js"></script>
<script type="text/javascript" src="assets/js/jquery.isotope.min.js?v=1.5.26"></script>
<script type="text/javascript" src="assets/js/jquery.singlePageNav.min.js"></script>
<script type="text/javascript" src="assets/js/main.js"></script>